on: [push]
jobs:
  deploy_job:
    runs-on: ubuntu-latest
    name: build&deploy
    steps:
      # To use this repository's private action, you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: yarn
      - name: Install Gulp
        run: yarn global add gulp
      - name: Build
        run: gulp build
      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: w018b260.kasserver.com
          username: w018b260
          password: ${{ secrets.ftp_password }}
          local-dir: dist/
          server-dir: test.design-mai.de
